name: snowflake
description: snowflake for Dart.
version: 2.0.0
homepage: https://github.com/928799934/dart-snowflake

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
